package net.lax1dude.eaglercraft.backend.server.api;

public enum EnumPipelineEvent {
	EAGLER_STATE_HTTP_REQUEST,
	EAGLER_STATE_WEBSOCKET_PLAYER,
	EAGLER_INJECTED_FRAME_HANDLERS,
	EAGLER_STATE_WEBSOCKET_QUERY,
	EAGLER_INJECTED_MESSAGE_CONTROLLER,
	EAGLER_INJECTED_REWIND_HANDLERS,
	EAGLER_DISABLE_COMPRESSION_HACK,
	EAGLER_OUTBOUND_THROW_REMOVED,
	EAGLER_HANDSHAKE_COMPLETE
}
